// Generates src/ds/tokens.css from the design system's tokens.json, so the app never hard-codes a color.
import { readFileSync, writeFileSync } from "node:fs";
const src = new URL("../../design-system/project/tokens.json", import.meta.url);
const out = new URL("../src/ds/tokens.css", import.meta.url);
const t = JSON.parse(readFileSync(src, "utf8"));

const dark = [], light = [], shared = [];
for (const c of t.color.tokens) { dark.push(`--${c.name}: ${c.value.dark};`); light.push(`--${c.name}: ${c.value.light};`); }
for (const [k, v] of Object.entries(t.type.families)) shared.push(`--font-${k}: ${v};`);
for (const s of t.spacing.tokens) shared.push(`--${s.name}: ${s.value};`);
for (const r of t.radius.tokens) shared.push(`--${r.name}: ${r.value};`);
for (const d of t.duration.tokens) shared.push(`--${d.name}: ${d.value};`);

const css = `/* Generated by scripts/gen-tokens.mjs from design-system/project/tokens.json. Do not edit. */
:root { ${shared.join(" ")} }
:root, [data-theme="dark"] { color-scheme: dark; ${dark.join(" ")} }
[data-theme="light"] { color-scheme: light; ${light.join(" ")} }
`;
writeFileSync(out, css);
console.log("tokens.css: %d colors, %d shared", t.color.tokens.length, shared.length);
